version: '3.4'

services:
  colossalgame:
    image: ${DOCKER_REGISTRY-}colossalgame
    build:
      context: .
      dockerfile: ColossalGame/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on: 
        - "db"
    ports:
      - "80"
      - "443"
    volumes:
      - ./.aspnet/https:/https/:ro
  db:
      container_name: mongo
      image: mongo
      restart: always
      ports:
        - "27017:27017"